=== IzegnaneAbdenacer/Technologie-XML/tpReleveBanquaire/releveBancaire.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" >
<xsd:element name="releves">
    <xsd:complexType>
        <xsd:sequence>
            <xsd:element name="releve" minOccurs="1" maxOccurs="unbounded" type="typeReleve"></xsd:element>
        </xsd:sequence>
    </xsd:complexType>
</xsd:element>
    <xsd:complexType name="typeReleve">
        <xsd:sequence>
            <xsd:element name="operations" minOccurs="1" maxOccurs="unbounded" type="typeOperations"></xsd:element>
        </xsd:sequence>
        <xsd:attribute name="rib" type="xsd:string" use="required"></xsd:attribute>
        <xsd:attribute name="dateReleve" type="xsd:date" use="required"></xsd:attribute>
        <xsd:attribute name="solde" type="xsd:double" use="required"></xsd:attribute>
    </xsd:complexType>
   <xsd:complexType name="typeOperations">
       <xsd:sequence>
           <xsd:element name="operation" minOccurs="1" maxOccurs="unbounded" type="typeOperation"></xsd:element>              
           
       </xsd:sequence>
       <xsd:attribute name="dateDebut" type="xsd:date" use="required"></xsd:attribute>
       <xsd:attribute name="dateFin" type="xsd:date" use="required"></xsd:attribute>
   </xsd:complexType>
    <xsd:complexType name="typeOperation">
        <xsd:attribute name="type" default="DEBIT">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:enumeration value="CREDIT"></xsd:enumeration>
                    <xsd:enumeration value="DEBIT"></xsd:enumeration>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
        <xsd:attribute name="date" type="xsd:date" use="required"></xsd:attribute>
        <xsd:attribute name="montant" type="xsd:int" use="required"></xsd:attribute>
        <xsd:attribute name="description" type="xsd:string" use="required"></xsd:attribute>
    </xsd:complexType>
</xsd:schema>

=== IzegnaneAbdenacer/Technologie-XML/tpReleveBanquaire/releveBancaireXSD.xml
<?xml version="1.0" encoding="UTF-8"?>
<releves xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="file:/C:/Users/m/OneDrive/Desktop/M1%20Master%20II-BDCC/Semestre.7/Technologie%20XML%20et%20Web%20services/TPs/tpReleveBanquaire/releveBancaire.xsd">
    <releve rib="011112222333344445555666" dateReleve="2021-11-10" solde="14500">
        <operations dateDebut="2021-01-01" dateFin="2021-01-30">
            <operation date="2021-01-01" montant="9000" description="Vers Especes" type="CREDIT"/>
            <operation date="2021-01-11" montant="3400" description="Cheque Guichet" type="CREDIT"/>
            <operation date="2021-01-15" montant="120" description="Prelevement Assurance" type="CREDIT"/>
            <operation date="2021-01-25" montant="70000" description="Virement" type="CREDIT"/>
        </operations>
    </releve>
    <releve rib="011112222333344445555777" dateReleve="2021-11-10" solde="14500">
        <operations dateDebut="2021-02-28" dateFin="2021-01-30">
            <operation date="2021-01-01" montant="9000" description="Vers Especes" type="CREDIT"/>
            <operation date="2021-01-11" montant="3400" description="Cheque Guichet" type="DEBIT"/>
            <operation date="2021-01-15" montant="120" description="Prelevement Assurance" type="CREDIT"/>
            <operation date="2021-01-25" montant="70000" description="Virement" type="DEBIT"/>
        </operations>
    </releve>
</releves>
