=== IzegnaneAbdenacer/Technologie-XML/tpReleveBanquaire/releveBancaire.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT releves (releve+)>
<!ELEMENT releve (operations+)>
<!ELEMENT operations (operation+) >
<!ELEMENT operation EMPTY >
<!ATTLIST releve
           RIB CDATA #REQUIRED
           dateReleve CDATA #REQUIRED
           solde CDATA #REQUIRED>
<!ATTLIST operations
           dateDebut CDATA #REQUIRED
           dateFin CDATA #REQUIRED>
<!ATTLIST  operation
           type (CREDIT|DEBIT) "DEBIT"
           date CDATA #REQUIRED
           montant CDATA #REQUIRED
           description CDATA #REQUIRED>

=== IzegnaneAbdenacer/Technologie-XML/tpReleveBanquaire/releveBancaire.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE releves SYSTEM "file:/C:/Users/m/OneDrive/Desktop/M1%20Master%20II-BDCC/Semestre.7/Technologie%20XML%20et%20Web%20services/TPs/tpReleveBanquaire/releveBancaire.dtd">
<releves>
    <releve RIB="011112222333344445555666" dateReleve="2021-11-10" solde="14500">
        <operations dateDebut="2021-01-01" dateFin="2021-01-30">
            <operation date="2021-01-01" montant="9000" description="Vers Especes" type="DEBIT"/>
            <operation date="2021-01-11" montant="3400" description="Cheque Guichet" type="CREDIT"/>
            <operation date="2021-01-15" montant="120" description="Prelevement Assurance" type="DEBIT"/>
            <operation date="2021-01-25" montant="70000" description="Virement" type="CREDIT"/>
        </operations>
    </releve>
    <releve RIB="011112222333344445555777" dateReleve="2021-11-10" solde="86253">
        <operations dateDebut="2021-02-01" dateFin="2021-02-28">
            <operation date="2021-02-01" montant="746373" description="Vers Especes" type="CREDIT"/>
            <operation date="2021-02-11" montant="653647" description="Cheque Guichet" type="DEBIT"/>
            <operation date="2021-01-20" montant="8653" description="Prelevement Assurance" type="CREDIT"/>
            <operation date="2021-01-27" montant="52463" description="Virement" type="DEBIT"/>
        </operations>
    </releve>
</releves>
