=== IzegnaneAbdenacer/Technologie-XML/tpTelecom/marocTelecom.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT operateur (client+)>
<!ELEMENT client (abonnement+) >
<!ELEMENT abonnement (facture+) >
<!ELEMENT facture EMPTY >
<!ATTLIST client
               code CDATA #REQUIRED
               nom NMTOKEN #REQUIRED>
<!ATTLIST abonnement
                num CDATA #REQUIRED
                type (GSM | FIXE) "FIXE"
                dateAb CDATA #REQUIRED>
<!ATTLIST facture
                numFact CDATA #REQUIRED
                dateFact CDATA #REQUIRED
                montant CDATA #REQUIRED
                regle (oui | non) "non">

=== IzegnaneAbdenacer/Technologie-XML/tpTelecom/marocTelecom.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE operateur SYSTEM "file:/C:/Users/m/OneDrive/Desktop/XMLTP/tpMarocTeleocm/marocTelecom.dtd">
<operateur>
    <client code="01" nom="Bakas">
        <abonnement num="01" dateAb="2020-01-01" type="GSM">
            <facture numFact="01" dateFact="2020-02-01" montant="1000" regle="oui"/>
        </abonnement>
        <abonnement num="02" dateAb="2020-01-01" type="FIXE">
            <facture numFact="01" dateFact="2020-02-01" montant="2000" regle="non"/>
        </abonnement>
    </client>
    <client code="02" nom="Izegnane">
        <abonnement num="01" dateAb="2020-01-01" type="GSM">
            <facture numFact="01" dateFact="2020-02-01" montant="1000" regle="oui"/>
        </abonnement>
        <abonnement num="02" dateAb="2020-01-01" type="FIXE">
            <facture numFact="01" dateFact="2020-02-01" montant="2000" regle="non"/>
        </abonnement>
    </client>
</operateur>
